# src/swagger/swagger.yml

openapi: 3.0.0
info:
  title: Documentación de la API REST Modular
  description: API centralizada para autenticación y administración de usuarios.
  version: 1.0.0

servers:
  - url: /api
    description: Servidor de la API

# ---------------------------------------------
# 1. IMPORTACIÓN DE COMPONENTES (Schemas, Security, Responses)
# ---------------------------------------------
components:
  {} # Debe ser un objeto vacío para que swagger-jsdoc pueda fusionar los componentes.

# ---------------------------------------------
# 2. IMPORTACIÓN DE RUTAS (Endpoints)
# ---------------------------------------------
paths:
  {} # Debe ser un objeto vacío para que swagger-jsdoc pueda fusionar las rutas.
